
# version: '3.8'
###
services:
  postgres:
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - miniodata:/data
    expose:
      - "9000"
      - "9001"
    ports:
      - "9001:9001"

  backend:
    build: ./backend
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${MINIO_BUCKET}
    expose:
      - "8080"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
      HOST: 0.0.0.0
    expose:
      - "3000"

  nginx:
    build: ./nginx
    depends_on:
      - frontend
      - backend
      - mediamtx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/etc:/etc/letsencrypt

  mediamtx:
    image: bluenviron/mediamtx:latest
    restart: unless-stopped
    environment:
      MTX_PROTOCOLS: "tcp"
      MTX_HLS: "yes"
      MTX_WEBRTC: "yes"
      MTX_WHIP: "yes"
      MTX_WEBRTCADDRESS: ":8889"
    expose:
      - "8888" # HTTP (API, HLS, WHIP)
      - "8889" # WebRTC (WHIP/WHEP)
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml:ro
    # Uncomment to persist recordings/configs if later needed
    # volumes:
    #   - ./mediamtx:/data

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/etc:/etc/letsencrypt
    entrypoint: /bin/sh
    command: -c "trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew --webroot -w /var/www/certbot --deploy-hook \"nginx -s reload\"; done"

volumes:
  pgdata:
  miniodata:
